```{r solution, echo = FALSE, results = "hide",cache=TRUE}
library(GetQuandlData)

id_series <- c(COFFEE = 'CEPEA/COFFEE_A')

# set api key (make sure you got your own!)
my_api_key <- readLines('~/Dropbox/98-pass_and_bash/.quandl_api.txt')

first_date <- '2010-01-01'
last_date <- '2020-12-31'

df_coffee <- get_Quandl_series(id_in = id_series, 
                               first_date = first_date,
                               last_date = last_date,
                               api_key = my_api_key,
                               do_cache = TRUE)

# find most recent
idx <- which.max(df_coffee$ref_date)
my_sol <- as.numeric(df_coffee$`Cash Price US$`[idx])
```

```{r datageneration, echo = FALSE, results = "hide"}
my_answer <- make_random_answers(my_sol)

#check_answers(my_answers)
```

Question
========

Caso não o tenha feito, crie um perfil no site do [Quandl](https://www.quandl.com/) e baixe os dados de preços de café arábica no banco de dados do CEPEA (Centro de Estudos Avançados em Economia Aplicada) entre  `r first_date` e `r last_date`. Qual é o valor do preço mais recente?

Solution
================

```{r solution, eval=FALSE}
```


Meta-information
================
extype: num
exsolution: `r my_sol`
exname: "quandl"
exshuffle: TRUE

