---
title: "Analyzing Financial and Economic Data with R"
author: "Marcelo S. Perlin"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
  word_document: default
subtitle: "Chapter 01 - Introduction"
---

## Exercises

**01. Use [Google](https://www.google.com/search?q=R+groups+in+my+city) to search for R groups in your region. Verify if there are frequent meetings and, if you so desire, go to one and make new friends.**

**02. Once you have R and RStudio installed, head over to the [CRAN package website](https://cloud.r-project.org/web/packages/available_packages_by_date.html)^[https://cloud.r-project.org/web/packages/available_packages_by_date.html] and search for computer technologies that you use in your current work. For example, if you use [Google Sheets](https://www.google.com/sheets/about/)^[https://www.google.com/sheets/about/] extensively in your work, you'll soon find there is a package in CRAN that can interact with it by creating and reading cloud-based spreadsheets.  **

**03. If you work in an institution with data infrastructure, talk to the IT department and seek to understand what type of data technology is being currently used. Check if it's possible, from R, to connect to the databases of your company and import the tables. No need for writing any code yet, just make sure the technology is available.**

**03. Head over to the [RBloggers](https://www.r-bloggers.com/)^[https://www.r-bloggers.com/] website and search for a topic of your interest, such as, "Tennis" or "investments". Read at least two or three articles that interest you.**

  
