```{r data generation, echo = FALSE, results = "hide"}
my.seed <- sample(1:100, 1)
set.seed(my.seed)
N <- 10000
my.x <- runif(N)*sample(c(-0.5, 1), size = N, replace = TRUE)

threshold <- floor(sample(10:50, 1))

res <- 0
i <- 0
while (res < threshold) {
  
  i <- i + 1
  res <- res + my.x[i]
  
}

sol.q <- i
rnd.vec <- afedR::afedR_gen_rnd_vec()

my.answers <- format(floor(sol.q*rnd.vec))
```


Question
========

Using _my.seed = `r my.seed`_, create a vector with the following code:

```{r, eval=FALSE}
set.seed(my.seed)
N <- 10000
my.x <- runif(N)*sample(c(-0.5, 1), size = N, replace = TRUE)
```

Using a `while` command, what is the first element where the cumulative sum of `my.x` reaches a value higher than `r threshold`?

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(my.answers, markup = "markdown")
```



Meta-information
================
extype: schoice
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: while loop
exshuffle: TRUE
