```{r datageneration, echo = FALSE, results = "hide"}
my_answers <- c('S+', 
                'C++',
                'Python',
                'Matlab',
                'Javascript')

book_site_zip <- adfeR::get_links_book()$book_site_zip
#check_answers(my_answers)
```

Question
========

Utilize o R para baixar o arquivo compactado com o material do livro, disponível nesse [link](`r book_site_zip`)^[`r book_site_zip`]. Salve o mesmo como um arquivo na pasta temporária da sessão (veja função `tempfile`).

```{r questionlist, echo = FALSE, results = "asis"}
exams::answerlist(my_answers, markup = "markdown")
```

Solution
================

```{r, eval=FALSE}
local_file <- tempfile(fileext = '.zip')
my_url <- 'https://www.msperlin.com/blog/files/pafdr%20files/Code_Data_pafdR.zip'

download.file(url = my_url, 
              destfile = local_file)

# check if exists
file.exists(local_file)
```


Meta-information
================
extype: string
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: "getwd"
exshuffle: TRUE

