```{r data generation, echo = FALSE, results = "hide"}
if (lan == 'en') {
  question.1 <- 'Consider the execution of the following R code:'
  question.2 <- 'Which of the following commands will replicate the contents of _my.objs_?'
  
}

if (lan == 'pt-br') {
  question.1 <- 'Considere a execução do seguinte código no R'
  question.2 <- 'Quais dos comandos abaixo replicaria o conteúdo de _my.objs_?'
}

my.answers <- c("c('x', 'y')",
                "c('my.objs')",
                'NA',
                "x",
                "y")
```


Question
========

```{r body, echo = FALSE, results = "asis"}
cat(paste(question.1,collapse = ""))
```

<pre><code>
rm(list = ls())
x=1:100
y=2:100
my.objs <- ls()
</code></pre>

```{r body2, echo = FALSE, results = "asis"}
cat(paste(question.2,collapse = ""))
```

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(my.answers, markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: about ls
exshuffle: TRUE
