```{r data generation, echo = FALSE, results = "hide"}
my.fct <- ls('package:base')

#remove fct with funky names
my.idx <- min(which(str_sub(my.fct,1,1)=='a'))
my.fct <- my.fct[my.idx:length(my.fct)]

my.fct <- my.fct[!stringr::str_detect(my.fct,'_')]

# remove fct related to print
my.fct <- my.fct[!stringr::str_detect(my.fct,'print')]

# remove fct related to cat
my.fct <- my.fct[!stringr::str_detect(my.fct,'cat')]

my.answers <- c('cat','print',sample(my.fct,3))

if (lan == 'en') {
  question <- 'What is the name of the function that parses (processes) and presents a text output in the prompt of R?'
}

if (lan == 'pt-br') {
  question <- 'Qual é o nome da função que processa e apresenta um texto no prompt do R?'
}
```



Question
========

```{r body, echo = FALSE, results = "asis"}
cat(paste(question,collapse = ""))
```


```{r questionlist, echo = FALSE, results = "asis"}
answerlist(my.answers, markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: about cat
exshuffle: TRUE
