```{r data generation, echo = FALSE, results = "hide"}
first.value <- sample(-50:20,1)
last.value <- sample(50:100,1)

my.idx <- first.value:last.value
 
idx.rnd <- sample(1:5,1)

x <- my.idx[idx.rnd]
y <- my.idx[length(my.idx)-2]
 
my.answers <- character(5)
my.answers[1] <- paste0('x = ',x, ', ','y = ',y)
my.answers[2] <- paste0('x = ',y, ', ','y = ',x)
my.answers[3] <- paste0('x = ',x+5, ', ','y = ',y-10)
my.answers[4] <- paste0('x = ',x-2, ', ','y = ',y+10)
my.answers[5] <- paste0('x = ',x+12, ', ','y = ',y+12)


if (lan == 'en') {
  question.1 <- 'Consider the following code.'
  question.2 <- 'Without the execution of the code, what is the content of objects x and y?
?'
}

if (lan == 'pt-br') {
  
  question.1 <- 'Considere o código a seguir.'
  question.2 <- 'Sem executar o código, qual é o conteúdo dos objetos x e y?'
}

```

Question
========

```{r body, echo = FALSE, results = "asis"}
cat(paste(question.1,collapse = ""))
```

<pre><code>
my.idx <- `r first.value`:`r last.value`
x <- my.idx[`r idx.rnd`]
y <- my.idx[length(my.idx)-2]
</code></pre>

```{r body2, echo = FALSE, results = "asis"}
cat(paste(question.2,collapse = ""))
```

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(my.answers, markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: x and y
exshuffle: TRUE
