```{r data generation, echo = FALSE, results = "hide"}
if (lan == 'en') {
  question.1 <- 'The following code was executed in R.'
  question.2 <- 'Which of the following commands will result in an error?'
  
}

if (lan == 'pt-br') {
  question.1 <- 'Dado que o código abaixo foi executado no R.'
  question.2 <- 'Quais dos comandos abaixo resultaria em um erro?'
}
```

Question
========

```{r body1, echo = FALSE, results = "asis"}
cat(paste(question.1,collapse = ""))
```

<pre><code>
my.vec <- runif(100)
</code></pre>

```{r body2, echo = FALSE, results = "asis"}
cat(paste(question.2, collapse = ""))
```

```{r questionlist, echo = FALSE, results = "asis"}
my.answers <- c("my.vec*'a'", 
                "my.vec + runif(100)",
                "my.vec + runif(101)",
                "my.vec[-1]",
                "my.vec[101]")
answerlist(my.answers, markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: about error
exshuffle: TRUE
