```{r data generation, echo = FALSE, results = "hide"}
my.date <- Sys.Date()

format(my.date,'%d/%m/%Y')

my.answers <- character(5)
my.answers[1] <- '.RData'
my.answers[2] <- '.R'
my.answers[3] <- '.Rmd'
my.answers[4] <- '.csv'
my.answers[5] <- '.Rproj'

#my.answers <- paste0('\\verb|',my.answers,'|')

if (lan == 'en') {
  question <- paste0('In a particular part of our code we used function _load_. What is extension of the file used as input in this function?')
}

if (lan == 'pt-br') {
  question <- paste0('Em uma parte particular de nosso código, o comando _load_ foi utilizado. Qual é a extensão do arquivo utilizado como input desta função?')
}

```

Question
========

```{r body, echo = FALSE, results = "asis"}
cat(paste(question,collapse = ""))
```

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(my.answers, markup = "markdown")
```


Meta-information
================
extype: schoice
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: about load
exshuffle: TRUE
