```{r data generation, echo = FALSE, results = "hide"}

if (lan == 'en') {
  question.1 <- 'If you are working in a directory of your computer called "C:/MyCode" and want to change the directory to a subfolder called "data", which of the following commands will do that?'
  
}

if (lan == 'pt-br') {
  question.1 <- 'Caso estejas trabalhando com o R em um diret칩rio do seu computador chamado _C:/MyCode_ e queira mudar o diret칩rio de trabalho para um subdiret칩rio chamado _data_, qual dos comandos abaixo ir치 atingir este objetivo?'
  
}

my.answers <- character()
my.answers[1] <- "setwd(paste0(getwd(),'/data'))"
my.answers[2] <- "setwd(paste(getwd(),'/data'))"
my.answers[3] <- "setwd(getwd())"
my.answers[4] <- "getwd(paste0(setwd(),'data'))"
my.answers[5] <- "getwd(paste(getwd(),'data'))"
```

Question
========

```{r body, echo = FALSE, results = "asis"}
cat(paste(question.1, collapse = ""))
```


```{r questionlist, echo = FALSE, results = "asis"}
answerlist(my.answers, markup = "markdown")
```


Meta-information
================
extype: schoice
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: about directory
exshuffle: TRUE
