```{r data generation, echo = FALSE, results = "hide"}

#possible.repo <- getCRANmirrors()$URL  # doenst work well for all repos

possible.repo <- c('https://cloud.r-project.org/',
                  'http://mirror.fcaglp.unlp.edu.ar/CRAN/',
                  'http://cran-r.c3sl.ufpr.br/',
                  'http://cran.stat.sfu.ca/',
                  'https://mirrors.dotsrc.org/cran/',
                  'https://mirrors.cicku.me/CRAN/',
                  'https://cran.ism.ac.jp/')

# the only one without giving error
possible.repo <- c('https://cloud.r-project.org/')
                   
my.repo <- sample(possible.repo, 1)
n.pkgs <- nrow(available.packages(repos = my.repo))

#n.pkgs <- 10000
sol.q <- n.pkgs

if (lan == 'en') {
  question.1 <- paste0('How many packages you can find today (',Sys.Date(),') in CRAN? Use the repository in ',
                       my.repo, ' for your answer. Be aware there might be small differences for the number of packages from one day to the next. Pick the answer that is closest to the found value.')
  
  my.answers <- paste0(floor(sol.q*afedR::afedR_gen_rnd_vec()), ' packages')

}

if (lan == 'pt-br') {
  question.1 <- paste0('Quantos pacotes existem hoje (',Sys.Date(),') no CRAN? Use o repositório em ',
                       my.repo,' para a sua resposta. Saiba que é possível que o número de pacotes tenha mudado entre um dia e outro. Assinale a resposta mais próxima do valor encontrado. ')
  
  my.answers <- paste0(floor(sol.q*afedR::afedR_gen_rnd_vec()), ' pacotes')

}

```


Question
========

```{r body, echo = FALSE, results = "asis"}
cat(paste(question.1, collapse = ""))
```
  

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(my.answers, markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: about pkgs in cran
exshuffle: TRUE
