```{r data generation, echo = FALSE, results = "hide"}
if (lan == 'en') {
  question.1 <- 'If we executed the following code in R, what would be the result?'
  
  my.answers <- character(5)
  my.answers[1] <- 'Object _my.f_ will hold all filenames in folder _data_ that have the _.csv_ extension. It will also display the names of the subfolders'
  my.answers[2] <-'Object _my.f_ will hold all objects from namespace _data_'
  my.answers[3] <- 'The object will return all files from folder _data_'
  my.answers[4] <- 'The call to _list.files_ will look for all filenames that start with _data_'
  my.answers[5] <- paste0('The object _my.f_ will show the number of packages in CRAN in next week, ', Sys.Date()+7)
}

if (lan == 'pt-br') {
  question.1 <- 'Caso fosse executado o seguinte código no R, qual seria o resultado ?'
  
  my.answers <- character(5)
  my.answers[1] <- 'Objeto _my.f_ armazena todos os nomes de arquivos no diretório _data_ que contenham a extensão _.csv_. O comando também mostrará o nome dos subdiretórios de cada arquivo'
  my.answers[2] <-'Objeto _my.f_ armazenará todos os objetos do _namespace_ _data_'
  my.answers[3] <- 'O objeto irá retornar todos os nomes dos arquivos no folder _data_'
  my.answers[4] <- 'O resultado será um objeto que terá em seu conteúdo todos os nomes de arquivos que começam com o texto _data_'
  my.answers[5] <- paste0('O objeto _my.f_ irá mostrar o número de pacotes no CRAN para a próxima semana, ', Sys.Date()+7)
  
}

```

Question
========

```{r body, echo = FALSE, results = "asis"}
cat(paste(question.1, collapse = ""))
```

<pre><code>
my.f <- list.files(path = 'data', pattern = '*.csv',full.names = TRUE)
</code></pre>


```{r body2, echo=FALSE, eval=FALSE}
my.f <- list.files(path = 'data', pattern = '*.csv',full.names = TRUE)
```

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(my.answers, markup = "markdown")
```


Meta-information
================
extype: schoice
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: t statistic
exshuffle: TRUE
