```{r data generation, echo = FALSE, results = "hide"}
my.nrows <- sample(5:10,1)
my.ncols <- sample(3:5,1)
M <- matrix(runif(my.nrows*my.ncols), 
            nrow = my.nrows, 
            ncol = my.ncols)

my.nrows <- nrow(M)
my.ncols <- ncol(M)
sol.q <- M[my.ncols-1,my.ncols]

my.answers <- character()
my.answers[1] <- sol.q 
my.answers[2] <- M[sample(1:my.nrows,1),my.ncols-2]
my.answers[3] <- M[my.ncols,my.ncols-2]
my.answers[4] <- M[my.ncols-1,1]
my.answers[5] <- M[1,1]

if (lan == 'en') {
  question.1 <- 'Consider the following matrix M:'
  question.2 <- 'If we created a new object called sol.q with the code:'
  question.3 <- 'What would be its contents ? (You should be able to find the solution without any coding).'
  
}

if (lan == 'pt-br') {
  
  question.1 <- 'Considere a seguinte matriz:'
  question.2 <- 'Caso criássemos um objeto chamado \\verb|sol.q| com o código:'
  question.3 <- 'qual seria o seu conteúdo? (você deve achar a solução sem a execução do código).'
  
}

```

Question
========

```{r body, echo = FALSE, results = "asis"}
cat(paste(question.1,collapse = ""))
```

```{r tab, echo=FALSE}
print(M)
```

```{r body2, echo = FALSE, results = "asis"}
cat(paste(question.2,collapse = ""))
```

<pre><code>
my.nrows <- nrow(M)
my.ncols <- ncol(M)
sol.q <- M[my.ncols-1,my.ncols]
</pre></code>

```{r body3, echo = FALSE, results = "asis"}
cat(paste(question.3,collapse = ""))
```


```{r questionlist, echo = FALSE, results = "asis"}
answerlist(my.answers, markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: selecting values
exshuffle: TRUE
