```{r datageneration, echo = FALSE, results = "hide"}
my.seed <- sample(1:100,1)

if (lan == 'en') {
  question.1 <- 'A student executed the following R code:'
  question.2 <- paste0('If my.seed = ',my.seed,', what is the content of object _x_?')
  
}

if (lan == 'pt-br') {
  question.1 <- 'Um estudante executou o seguinte código do R:'
  question.2 <- paste0('Se my.seed = ',my.seed,', qual é o conteúdo do object _x_?')
}

set.seed(my.seed)
y <- sample(1:10, 3)
y <- y[c(1,3)]
x <- y[2]

my.answers <- character()
my.answers[1] <- x
my.answers[2] <- NA
my.answers[3] <- y[1]
my.answers[4] <- y[1]+3
my.answers[5] <- x+1
```

Question
========

```{r body1, echo = FALSE, results = "asis"}
cat(paste(question.1, collapse = ""))
```

```{r body2, eval=FALSE}
set.seed(my.seed)
y <- sample(1:10, 3)
y <- y[c(1,3)]
x <- y[2]
```

```{r body3, echo = FALSE, results = "asis"}
cat(paste(question.2, collapse = ""))
```

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(my.answers, markup = "markdown")
```


Meta-information
================
extype: schoice
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: about x
exshuffle: TRUE
