```{r data generation, echo = FALSE, results = "hide"}
my.nrows <- sample(5:10,1)
my.ncols <- sample(2:5,1)

x <- matrix(runif(my.nrows*my.ncols), nrow = my.nrows, ncol = my.ncols)

my.answers <- character()
my.answers[1] <- paste(dim(x)[1], ncol(x), length(x), sep = ', ')
my.answers[2] <- paste(dim(x)[2], ncol(x)-1, length(x), sep = ', ')
my.answers[3:5] <- paste(dim(x)[1]+sample(1:10,3), 
                         ncol(x)+sample(-10:-5,3), 
                         length(x)+sample(-5:5,1), 
                         sep = ', ')

if (lan == 'en') {
  question.1 <- 'Consider the creation of the following matrix M:'
  question.2 <- 'If we executed in R the commands _dim(M)[1]_, _ncol(M)_ and _length(M)_ in that exact order, what would be the result?'
  
}

if (lan == 'pt-br') {
  
  question.1 <- 'Considere a criação da seguinte matriz M:'
  question.2 <- 'Caso executássemos os comandos  _dim(M)[1]_, _ncol(M)_ e _length(M)_, nessa mesma ordem, qual seria o resultado?'
}

```


Question
========

```{r body, echo = FALSE, results = "asis"}
cat(paste(question.1,collapse = ""))
```

```{r tab, echo=FALSE}
print(x)
```

```{r body2, echo = FALSE, results = "asis"}
cat(paste(question.2,collapse = ""))
```

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(my.answers, markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: about dim
exshuffle: TRUE
